// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Toci.Haia.Database.Persistence;

#nullable disable

namespace Toci.Haia.Database.Persistence.Migrations
{
    [DbContext(typeof(ComedyDbContext))]
    [Migration("20241113210414_AddUserAndPreferencesTables")]
    partial class AddUserAndPreferencesTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Satyra"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Parodia"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ironia"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Humor czarny"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Humor absurdalny"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Słowna gra"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Karykatura"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Humor polityczny"
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatRoomId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChatRoomId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.ChatRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChatRooms");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.ComedyText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ChildTextId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CommentTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ParentTextId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ComedyTexts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Author_1",
                            CommentTimestamp = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8173),
                            Text = "Sample Comedy Text 1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Author_2",
                            CommentTimestamp = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8179),
                            Text = "Sample Comedy Text 2"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Author_3",
                            CommentTimestamp = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8181),
                            Text = "Sample Comedy Text 3"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Author_4",
                            CommentTimestamp = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8183),
                            Text = "Sample Comedy Text 4"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Author_5",
                            CommentTimestamp = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8185),
                            Text = "Sample Comedy Text 5"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Author_6",
                            CommentTimestamp = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8187),
                            Text = "Sample Comedy Text 6"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Author_7",
                            CommentTimestamp = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8189),
                            Text = "Sample Comedy Text 7"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Author_8",
                            CommentTimestamp = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8191),
                            Text = "Sample Comedy Text 8"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Author_9",
                            CommentTimestamp = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8193),
                            Text = "Sample Comedy Text 9"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Author_10",
                            CommentTimestamp = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8196),
                            Text = "Sample Comedy Text 10"
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ComedyTextId")
                        .HasColumnType("integer");

                    b.Property<int?>("ComedyTextId1")
                        .HasColumnType("integer");

                    b.Property<int>("CommentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CommentTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GroupPostId")
                        .HasColumnType("integer");

                    b.Property<int>("JokeId")
                        .HasColumnType("integer");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComedyTextId");

                    b.HasIndex("ComedyTextId1");

                    b.HasIndex("CommentId");

                    b.HasIndex("GroupPostId");

                    b.HasIndex("JokeId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 0,
                            CommentTimestamp = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8285),
                            CreatedAt = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8280),
                            GroupPostId = 0,
                            JokeId = 0,
                            PostId = 0,
                            Text = "Sample Comment 1",
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 0,
                            CommentTimestamp = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8288),
                            CreatedAt = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8287),
                            GroupPostId = 0,
                            JokeId = 0,
                            PostId = 0,
                            Text = "Sample Comment 2",
                            UserId = 0
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 0,
                            CommentTimestamp = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8289),
                            CreatedAt = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8288),
                            GroupPostId = 0,
                            JokeId = 0,
                            PostId = 0,
                            Text = "Sample Comment 3",
                            UserId = 0
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 0,
                            CommentTimestamp = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8290),
                            CreatedAt = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8289),
                            GroupPostId = 0,
                            JokeId = 0,
                            PostId = 0,
                            Text = "Sample Comment 4",
                            UserId = 0
                        },
                        new
                        {
                            Id = 5,
                            CommentId = 0,
                            CommentTimestamp = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8292),
                            CreatedAt = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8291),
                            GroupPostId = 0,
                            JokeId = 0,
                            PostId = 0,
                            Text = "Sample Comment 5",
                            UserId = 0
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 0,
                            CommentTimestamp = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8293),
                            CreatedAt = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8292),
                            GroupPostId = 0,
                            JokeId = 0,
                            PostId = 0,
                            Text = "Sample Comment 6",
                            UserId = 0
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 0,
                            CommentTimestamp = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8295),
                            CreatedAt = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8294),
                            GroupPostId = 0,
                            JokeId = 0,
                            PostId = 0,
                            Text = "Sample Comment 7",
                            UserId = 0
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 0,
                            CommentTimestamp = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8296),
                            CreatedAt = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8295),
                            GroupPostId = 0,
                            JokeId = 0,
                            PostId = 0,
                            Text = "Sample Comment 8",
                            UserId = 0
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 0,
                            CommentTimestamp = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8298),
                            CreatedAt = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8297),
                            GroupPostId = 0,
                            JokeId = 0,
                            PostId = 0,
                            Text = "Sample Comment 9",
                            UserId = 0
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 0,
                            CommentTimestamp = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8299),
                            CreatedAt = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8298),
                            GroupPostId = 0,
                            JokeId = 0,
                            PostId = 0,
                            Text = "Sample Comment 10",
                            UserId = 0
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Friendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FriendId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserId");

                    b.ToTable("Friendships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FriendId = 2,
                            IsAccepted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            FriendId = 3,
                            IsAccepted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            FriendId = 4,
                            IsAccepted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            FriendId = 5,
                            IsAccepted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            FriendId = 6,
                            IsAccepted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            FriendId = 7,
                            IsAccepted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            FriendId = 8,
                            IsAccepted = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            FriendId = 9,
                            IsAccepted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            FriendId = 10,
                            IsAccepted = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            FriendId = 1,
                            IsAccepted = false,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.GptJoke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JokeText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReferenceId")
                        .HasColumnType("integer");

                    b.Property<int>("ReferenceKind")
                        .HasColumnType("integer");

                    b.Property<int>("RequestingUserId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GptJokes");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.GroupPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupPostId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Joke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Jokes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 0,
                            CreatedAt = new DateTime(2024, 11, 13, 21, 4, 11, 711, DateTimeKind.Utc).AddTicks(8688),
                            Text = "Dlaczego niebo jest niebieskie? Bo programista jeszcze nie skończył debugować!",
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 0,
                            CreatedAt = new DateTime(2024, 11, 13, 21, 4, 11, 711, DateTimeKind.Utc).AddTicks(8693),
                            Text = "Dlaczego komputer był smutny? Bo miał zbyt dużo problemów!",
                            UserId = 0
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CommentId = 5,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 6,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 7,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 8,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 9,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 10,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.PostInteraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InteractionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<int>("TimeSpentMilliseconds")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostInteractions");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Reaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommentId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupPostId")
                        .HasColumnType("integer");

                    b.Property<int?>("JokeId")
                        .HasColumnType("integer");

                    b.Property<string>("ReactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("GroupPostId");

                    b.HasIndex("JokeId");

                    b.HasIndex("UserId", "JokeId")
                        .IsUnique();

                    b.ToTable("Reactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupPostId = 0,
                            JokeId = 1,
                            ReactionType = "like",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            GroupPostId = 0,
                            JokeId = 1,
                            ReactionType = "superlike",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            GroupPostId = 0,
                            JokeId = 2,
                            ReactionType = "meh",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.SocialLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("SocialLogins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LinkedAt = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8478),
                            Provider = "Google",
                            ProviderUserId = "google_user_1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            LinkedAt = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8483),
                            Provider = "Facebook",
                            ProviderUserId = "facebook_user_1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            LinkedAt = new DateTime(2024, 11, 13, 21, 4, 11, 714, DateTimeKind.Utc).AddTicks(8485),
                            Provider = "GitHub",
                            ProviderUserId = "github_user_2",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameSurname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserGroupId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.UserCategoryPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("ReactionCount")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCategoryPreferences");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.UserPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("PreferenceLevel")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserId1");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Interests")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserProfile");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Interests = "Interests_1",
                            ProfilePictureUrl = "https://example.com/user1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Interests = "Interests_2",
                            ProfilePictureUrl = "https://example.com/user2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Interests = "Interests_3",
                            ProfilePictureUrl = "https://example.com/user3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Interests = "Interests_4",
                            ProfilePictureUrl = "https://example.com/user4.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Interests = "Interests_5",
                            ProfilePictureUrl = "https://example.com/user5.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Interests = "Interests_6",
                            ProfilePictureUrl = "https://example.com/user6.jpg"
                        },
                        new
                        {
                            Id = 7,
                            Interests = "Interests_7",
                            ProfilePictureUrl = "https://example.com/user7.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Interests = "Interests_8",
                            ProfilePictureUrl = "https://example.com/user8.jpg"
                        },
                        new
                        {
                            Id = 9,
                            Interests = "Interests_9",
                            ProfilePictureUrl = "https://example.com/user9.jpg"
                        },
                        new
                        {
                            Id = 10,
                            Interests = "Interests_10",
                            ProfilePictureUrl = "https://example.com/user10.jpg"
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.ChatMessage", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.ChatRoom", "ChatRoom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.ComedyText", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.ComedyText", "ChildComedyText")
                        .WithOne("ParentComedyText")
                        .HasForeignKey("Toci.Haia.Database.Persistence.ComedyText", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.User", null)
                        .WithMany("ComedyTexts")
                        .HasForeignKey("UserId");

                    b.Navigation("ChildComedyText");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Comment", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.ComedyText", null)
                        .WithMany("Comments")
                        .HasForeignKey("ComedyTextId");

                    b.HasOne("Toci.Haia.Database.Persistence.ComedyText", null)
                        .WithMany("Replies")
                        .HasForeignKey("ComedyTextId1");

                    b.HasOne("Toci.Haia.Database.Persistence.Comment", null)
                        .WithMany("Replies")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.GroupPost", null)
                        .WithMany("Comments")
                        .HasForeignKey("GroupPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.Joke", null)
                        .WithMany("Comments")
                        .HasForeignKey("JokeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Friendship", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.User", "Friend")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.GptJoke", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.GroupPost", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.UserGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Joke", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Like", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Post", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.UserGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.PostInteraction", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.GroupPost", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Reaction", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Toci.Haia.Database.Persistence.GroupPost", null)
                        .WithMany("Reactions")
                        .HasForeignKey("GroupPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.Joke", null)
                        .WithMany("Reactions")
                        .HasForeignKey("JokeId");

                    b.HasOne("Toci.Haia.Database.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.SocialLogin", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.User", "User")
                        .WithMany("SocialLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.User", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.UserGroup", null)
                        .WithMany("Users")
                        .HasForeignKey("UserGroupId");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.UserCategoryPreference", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.Category", "Category")
                        .WithMany("UserCategoryPreferences")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.User", "User")
                        .WithMany("UserCategoryPreferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.UserPreferences", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.User", null)
                        .WithOne("Preferences")
                        .HasForeignKey("Toci.Haia.Database.Persistence.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Category", b =>
                {
                    b.Navigation("UserCategoryPreferences");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.ChatRoom", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.ComedyText", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ParentComedyText")
                        .IsRequired();

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Comment", b =>
                {
                    b.Navigation("Reactions");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.GroupPost", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Joke", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.User", b =>
                {
                    b.Navigation("ComedyTexts");

                    b.Navigation("Messages");

                    b.Navigation("Preferences")
                        .IsRequired();

                    b.Navigation("SocialLogins");

                    b.Navigation("UserCategoryPreferences");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.UserGroup", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
