// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Toci.Haia.Database.Persistence;

#nullable disable

namespace Toci.Haia.Database.Persistence.Migrations
{
    [DbContext(typeof(ComedyDbContext))]
    [Migration("20240928170450_AddParentChildComedyText")]
    partial class AddParentChildComedyText
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Toci.Haia.Database.Persistence.ComedyText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ChildTextId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CommentTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ParentTextId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ComedyTexts");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ComedyTextId")
                        .HasColumnType("integer");

                    b.Property<int?>("ComedyTextId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CommentTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GptJoke")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("integer");

                    b.Property<string>("Snippet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SnippetAuthor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SnippetTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComedyTextId");

                    b.HasIndex("ComedyTextId1");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Friendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FriendId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserId");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.ComedyText", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.ComedyText", "ChildComedyText")
                        .WithOne("ParentComedyText")
                        .HasForeignKey("Toci.Haia.Database.Persistence.ComedyText", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.User", null)
                        .WithMany("ComedyTexts")
                        .HasForeignKey("UserId");

                    b.Navigation("ChildComedyText");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Comment", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.ComedyText", "ComedyText")
                        .WithMany("Comments")
                        .HasForeignKey("ComedyTextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.ComedyText", null)
                        .WithMany("Replies")
                        .HasForeignKey("ComedyTextId1");

                    b.HasOne("Toci.Haia.Database.Persistence.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId");

                    b.HasOne("Toci.Haia.Database.Persistence.User", null)
                        .WithMany("Comments")
                        .HasForeignKey("UserId");

                    b.Navigation("ComedyText");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Friendship", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.User", "Friend")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Like", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.ComedyText", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ParentComedyText")
                        .IsRequired();

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.User", b =>
                {
                    b.Navigation("ComedyTexts");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
