// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Toci.Haia.Database.Persistence;

#nullable disable

namespace Toci.Haia.Database.Persistence.Migrations
{
    [DbContext(typeof(ComedyDbContext))]
    [Migration("20241111135913_Init8")]
    partial class Init8
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Toci.Haia.Database.Persistence.ComedyText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ChildTextId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CommentTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ParentTextId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ComedyTexts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Author_1",
                            CommentTimestamp = new DateTime(2024, 11, 11, 13, 59, 13, 210, DateTimeKind.Utc).AddTicks(2765),
                            Text = "Sample Comedy Text 1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Author_2",
                            CommentTimestamp = new DateTime(2024, 11, 11, 13, 59, 13, 210, DateTimeKind.Utc).AddTicks(2769),
                            Text = "Sample Comedy Text 2"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Author_3",
                            CommentTimestamp = new DateTime(2024, 11, 11, 13, 59, 13, 210, DateTimeKind.Utc).AddTicks(2770),
                            Text = "Sample Comedy Text 3"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Author_4",
                            CommentTimestamp = new DateTime(2024, 11, 11, 13, 59, 13, 210, DateTimeKind.Utc).AddTicks(2772),
                            Text = "Sample Comedy Text 4"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Author_5",
                            CommentTimestamp = new DateTime(2024, 11, 11, 13, 59, 13, 210, DateTimeKind.Utc).AddTicks(2773),
                            Text = "Sample Comedy Text 5"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Author_6",
                            CommentTimestamp = new DateTime(2024, 11, 11, 13, 59, 13, 210, DateTimeKind.Utc).AddTicks(2774),
                            Text = "Sample Comedy Text 6"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Author_7",
                            CommentTimestamp = new DateTime(2024, 11, 11, 13, 59, 13, 210, DateTimeKind.Utc).AddTicks(2776),
                            Text = "Sample Comedy Text 7"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Author_8",
                            CommentTimestamp = new DateTime(2024, 11, 11, 13, 59, 13, 210, DateTimeKind.Utc).AddTicks(2777),
                            Text = "Sample Comedy Text 8"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Author_9",
                            CommentTimestamp = new DateTime(2024, 11, 11, 13, 59, 13, 210, DateTimeKind.Utc).AddTicks(2778),
                            Text = "Sample Comedy Text 9"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Author_10",
                            CommentTimestamp = new DateTime(2024, 11, 11, 13, 59, 13, 210, DateTimeKind.Utc).AddTicks(2780),
                            Text = "Sample Comedy Text 10"
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ComedyTextId")
                        .HasColumnType("integer");

                    b.Property<int?>("ComedyTextId1")
                        .HasColumnType("integer");

                    b.Property<int>("CommentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CommentTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JokeId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComedyTextId");

                    b.HasIndex("ComedyTextId1");

                    b.HasIndex("CommentId");

                    b.HasIndex("JokeId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Commenter_1",
                            CommentId = 0,
                            CommentTimestamp = new DateTime(2024, 11, 11, 13, 59, 13, 210, DateTimeKind.Utc).AddTicks(2810),
                            JokeId = 0,
                            Text = "Sample Comment 1",
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            Author = "Commenter_2",
                            CommentId = 0,
                            CommentTimestamp = new DateTime(2024, 11, 11, 13, 59, 13, 210, DateTimeKind.Utc).AddTicks(2813),
                            JokeId = 0,
                            Text = "Sample Comment 2",
                            UserId = 0
                        },
                        new
                        {
                            Id = 3,
                            Author = "Commenter_3",
                            CommentId = 0,
                            CommentTimestamp = new DateTime(2024, 11, 11, 13, 59, 13, 210, DateTimeKind.Utc).AddTicks(2815),
                            JokeId = 0,
                            Text = "Sample Comment 3",
                            UserId = 0
                        },
                        new
                        {
                            Id = 4,
                            Author = "Commenter_4",
                            CommentId = 0,
                            CommentTimestamp = new DateTime(2024, 11, 11, 13, 59, 13, 210, DateTimeKind.Utc).AddTicks(2816),
                            JokeId = 0,
                            Text = "Sample Comment 4",
                            UserId = 0
                        },
                        new
                        {
                            Id = 5,
                            Author = "Commenter_5",
                            CommentId = 0,
                            CommentTimestamp = new DateTime(2024, 11, 11, 13, 59, 13, 210, DateTimeKind.Utc).AddTicks(2818),
                            JokeId = 0,
                            Text = "Sample Comment 5",
                            UserId = 0
                        },
                        new
                        {
                            Id = 6,
                            Author = "Commenter_6",
                            CommentId = 0,
                            CommentTimestamp = new DateTime(2024, 11, 11, 13, 59, 13, 210, DateTimeKind.Utc).AddTicks(2819),
                            JokeId = 0,
                            Text = "Sample Comment 6",
                            UserId = 0
                        },
                        new
                        {
                            Id = 7,
                            Author = "Commenter_7",
                            CommentId = 0,
                            CommentTimestamp = new DateTime(2024, 11, 11, 13, 59, 13, 210, DateTimeKind.Utc).AddTicks(2820),
                            JokeId = 0,
                            Text = "Sample Comment 7",
                            UserId = 0
                        },
                        new
                        {
                            Id = 8,
                            Author = "Commenter_8",
                            CommentId = 0,
                            CommentTimestamp = new DateTime(2024, 11, 11, 13, 59, 13, 210, DateTimeKind.Utc).AddTicks(2828),
                            JokeId = 0,
                            Text = "Sample Comment 8",
                            UserId = 0
                        },
                        new
                        {
                            Id = 9,
                            Author = "Commenter_9",
                            CommentId = 0,
                            CommentTimestamp = new DateTime(2024, 11, 11, 13, 59, 13, 210, DateTimeKind.Utc).AddTicks(2829),
                            JokeId = 0,
                            Text = "Sample Comment 9",
                            UserId = 0
                        },
                        new
                        {
                            Id = 10,
                            Author = "Commenter_10",
                            CommentId = 0,
                            CommentTimestamp = new DateTime(2024, 11, 11, 13, 59, 13, 210, DateTimeKind.Utc).AddTicks(2830),
                            JokeId = 0,
                            Text = "Sample Comment 10",
                            UserId = 0
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Friendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FriendId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserId");

                    b.ToTable("Friendships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FriendId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            FriendId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            FriendId = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            FriendId = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            FriendId = 6,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            FriendId = 7,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            FriendId = 8,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            FriendId = 9,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            FriendId = 10,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            FriendId = 1,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Joke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Jokes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 11, 13, 59, 13, 209, DateTimeKind.Utc).AddTicks(6480),
                            Text = "Dlaczego niebo jest niebieskie? Bo programista jeszcze nie skończył debugować!",
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 11, 11, 13, 59, 13, 209, DateTimeKind.Utc).AddTicks(6483),
                            Text = "Dlaczego komputer był smutny? Bo miał zbyt dużo problemów!",
                            UserId = 0
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CommentId = 5,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 6,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 7,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 8,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 9,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 10,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Reaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommentId")
                        .HasColumnType("integer");

                    b.Property<int?>("JokeId")
                        .HasColumnType("integer");

                    b.Property<string>("ReactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("JokeId");

                    b.HasIndex("UserId", "JokeId")
                        .IsUnique();

                    b.ToTable("Reactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            JokeId = 1,
                            ReactionType = "like",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            JokeId = 1,
                            ReactionType = "superlike",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            JokeId = 2,
                            ReactionType = "meh",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.SocialLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("SocialLogins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LinkedAt = new DateTime(2024, 11, 11, 13, 59, 13, 210, DateTimeKind.Utc).AddTicks(2928),
                            Provider = "Google",
                            ProviderUserId = "google_user_1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            LinkedAt = new DateTime(2024, 11, 11, 13, 59, 13, 210, DateTimeKind.Utc).AddTicks(2930),
                            Provider = "Facebook",
                            ProviderUserId = "facebook_user_1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            LinkedAt = new DateTime(2024, 11, 11, 13, 59, 13, 210, DateTimeKind.Utc).AddTicks(2931),
                            Provider = "GitHub",
                            ProviderUserId = "github_user_2",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 11, 13, 59, 13, 210, DateTimeKind.Utc).AddTicks(2909),
                            Email = "user1@example.com",
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "hashed_password_1",
                            Username = "user1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 11, 11, 13, 59, 13, 210, DateTimeKind.Utc).AddTicks(2911),
                            Email = "user2@example.com",
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "hashed_password_2",
                            Username = "user2"
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Interests")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserProfile");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Interests = "Interests_1",
                            ProfilePictureUrl = "https://example.com/user1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Interests = "Interests_2",
                            ProfilePictureUrl = "https://example.com/user2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Interests = "Interests_3",
                            ProfilePictureUrl = "https://example.com/user3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Interests = "Interests_4",
                            ProfilePictureUrl = "https://example.com/user4.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Interests = "Interests_5",
                            ProfilePictureUrl = "https://example.com/user5.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Interests = "Interests_6",
                            ProfilePictureUrl = "https://example.com/user6.jpg"
                        },
                        new
                        {
                            Id = 7,
                            Interests = "Interests_7",
                            ProfilePictureUrl = "https://example.com/user7.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Interests = "Interests_8",
                            ProfilePictureUrl = "https://example.com/user8.jpg"
                        },
                        new
                        {
                            Id = 9,
                            Interests = "Interests_9",
                            ProfilePictureUrl = "https://example.com/user9.jpg"
                        },
                        new
                        {
                            Id = 10,
                            Interests = "Interests_10",
                            ProfilePictureUrl = "https://example.com/user10.jpg"
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.ComedyText", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.ComedyText", "ChildComedyText")
                        .WithOne("ParentComedyText")
                        .HasForeignKey("Toci.Haia.Database.Persistence.ComedyText", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.User", null)
                        .WithMany("ComedyTexts")
                        .HasForeignKey("UserId");

                    b.Navigation("ChildComedyText");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Comment", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.ComedyText", null)
                        .WithMany("Comments")
                        .HasForeignKey("ComedyTextId");

                    b.HasOne("Toci.Haia.Database.Persistence.ComedyText", null)
                        .WithMany("Replies")
                        .HasForeignKey("ComedyTextId1");

                    b.HasOne("Toci.Haia.Database.Persistence.Comment", null)
                        .WithMany("Replies")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.Joke", "Joke")
                        .WithMany("Comments")
                        .HasForeignKey("JokeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.User", null)
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Joke");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Friendship", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.User", "Friend")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Joke", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Like", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Reaction", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Toci.Haia.Database.Persistence.Joke", "Joke")
                        .WithMany("Reactions")
                        .HasForeignKey("JokeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Comment");

                    b.Navigation("Joke");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.SocialLogin", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.User", "User")
                        .WithMany("SocialLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.ComedyText", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ParentComedyText")
                        .IsRequired();

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Comment", b =>
                {
                    b.Navigation("Reactions");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Joke", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.User", b =>
                {
                    b.Navigation("ComedyTexts");

                    b.Navigation("Comments");

                    b.Navigation("SocialLogins");
                });
#pragma warning restore 612, 618
        }
    }
}
