// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Toci.Haia.Database.Persistence;

#nullable disable

namespace Toci.Haia.Database.Persistence.Migrations
{
    [DbContext(typeof(ComedyDbContext))]
    [Migration("20241106155137_UpdatedUserSeedData")]
    partial class UpdatedUserSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Toci.Haia.Database.Persistence.ComedyText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ChildTextId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CommentTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ParentTextId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ComedyTexts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Author_1",
                            CommentTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 393, DateTimeKind.Utc).AddTicks(9954),
                            Text = "Sample Comedy Text 1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Author_2",
                            CommentTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 393, DateTimeKind.Utc).AddTicks(9963),
                            Text = "Sample Comedy Text 2"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Author_3",
                            CommentTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 393, DateTimeKind.Utc).AddTicks(9965),
                            Text = "Sample Comedy Text 3"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Author_4",
                            CommentTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 393, DateTimeKind.Utc).AddTicks(9967),
                            Text = "Sample Comedy Text 4"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Author_5",
                            CommentTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 393, DateTimeKind.Utc).AddTicks(9969),
                            Text = "Sample Comedy Text 5"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Author_6",
                            CommentTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 393, DateTimeKind.Utc).AddTicks(9971),
                            Text = "Sample Comedy Text 6"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Author_7",
                            CommentTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 393, DateTimeKind.Utc).AddTicks(9973),
                            Text = "Sample Comedy Text 7"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Author_8",
                            CommentTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 393, DateTimeKind.Utc).AddTicks(9975),
                            Text = "Sample Comedy Text 8"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Author_9",
                            CommentTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 393, DateTimeKind.Utc).AddTicks(9976),
                            Text = "Sample Comedy Text 9"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Author_10",
                            CommentTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 393, DateTimeKind.Utc).AddTicks(9979),
                            Text = "Sample Comedy Text 10"
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ComedyTextId")
                        .HasColumnType("integer");

                    b.Property<int?>("ComedyTextId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CommentTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GptJoke")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("JokeId")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("integer");

                    b.Property<string>("Snippet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SnippetAuthor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SnippetTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComedyTextId");

                    b.HasIndex("ComedyTextId1");

                    b.HasIndex("JokeId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Commenter_1",
                            ComedyTextId = 1,
                            CommentTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 394, DateTimeKind.Utc).AddTicks(66),
                            GptJoke = "Generated Joke 1",
                            JokeId = 0,
                            Snippet = "Snippet 1",
                            SnippetAuthor = "SnippetAuthor_1",
                            SnippetTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 394, DateTimeKind.Utc).AddTicks(68),
                            Text = "Sample Comment 1",
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            Author = "Commenter_2",
                            ComedyTextId = 2,
                            CommentTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 394, DateTimeKind.Utc).AddTicks(78),
                            GptJoke = "Generated Joke 2",
                            JokeId = 0,
                            Snippet = "Snippet 2",
                            SnippetAuthor = "SnippetAuthor_2",
                            SnippetTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 394, DateTimeKind.Utc).AddTicks(79),
                            Text = "Sample Comment 2",
                            UserId = 0
                        },
                        new
                        {
                            Id = 3,
                            Author = "Commenter_3",
                            ComedyTextId = 3,
                            CommentTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 394, DateTimeKind.Utc).AddTicks(85),
                            GptJoke = "Generated Joke 3",
                            JokeId = 0,
                            Snippet = "Snippet 3",
                            SnippetAuthor = "SnippetAuthor_3",
                            SnippetTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 394, DateTimeKind.Utc).AddTicks(86),
                            Text = "Sample Comment 3",
                            UserId = 0
                        },
                        new
                        {
                            Id = 4,
                            Author = "Commenter_4",
                            ComedyTextId = 4,
                            CommentTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 394, DateTimeKind.Utc).AddTicks(90),
                            GptJoke = "Generated Joke 4",
                            JokeId = 0,
                            Snippet = "Snippet 4",
                            SnippetAuthor = "SnippetAuthor_4",
                            SnippetTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 394, DateTimeKind.Utc).AddTicks(90),
                            Text = "Sample Comment 4",
                            UserId = 0
                        },
                        new
                        {
                            Id = 5,
                            Author = "Commenter_5",
                            ComedyTextId = 5,
                            CommentTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 394, DateTimeKind.Utc).AddTicks(115),
                            GptJoke = "Generated Joke 5",
                            JokeId = 0,
                            Snippet = "Snippet 5",
                            SnippetAuthor = "SnippetAuthor_5",
                            SnippetTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 394, DateTimeKind.Utc).AddTicks(115),
                            Text = "Sample Comment 5",
                            UserId = 0
                        },
                        new
                        {
                            Id = 6,
                            Author = "Commenter_6",
                            ComedyTextId = 6,
                            CommentTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 394, DateTimeKind.Utc).AddTicks(120),
                            GptJoke = "Generated Joke 6",
                            JokeId = 0,
                            Snippet = "Snippet 6",
                            SnippetAuthor = "SnippetAuthor_6",
                            SnippetTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 394, DateTimeKind.Utc).AddTicks(120),
                            Text = "Sample Comment 6",
                            UserId = 0
                        },
                        new
                        {
                            Id = 7,
                            Author = "Commenter_7",
                            ComedyTextId = 7,
                            CommentTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 394, DateTimeKind.Utc).AddTicks(124),
                            GptJoke = "Generated Joke 7",
                            JokeId = 0,
                            Snippet = "Snippet 7",
                            SnippetAuthor = "SnippetAuthor_7",
                            SnippetTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 394, DateTimeKind.Utc).AddTicks(124),
                            Text = "Sample Comment 7",
                            UserId = 0
                        },
                        new
                        {
                            Id = 8,
                            Author = "Commenter_8",
                            ComedyTextId = 8,
                            CommentTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 394, DateTimeKind.Utc).AddTicks(128),
                            GptJoke = "Generated Joke 8",
                            JokeId = 0,
                            Snippet = "Snippet 8",
                            SnippetAuthor = "SnippetAuthor_8",
                            SnippetTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 394, DateTimeKind.Utc).AddTicks(128),
                            Text = "Sample Comment 8",
                            UserId = 0
                        },
                        new
                        {
                            Id = 9,
                            Author = "Commenter_9",
                            ComedyTextId = 9,
                            CommentTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 394, DateTimeKind.Utc).AddTicks(132),
                            GptJoke = "Generated Joke 9",
                            JokeId = 0,
                            Snippet = "Snippet 9",
                            SnippetAuthor = "SnippetAuthor_9",
                            SnippetTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 394, DateTimeKind.Utc).AddTicks(132),
                            Text = "Sample Comment 9",
                            UserId = 0
                        },
                        new
                        {
                            Id = 10,
                            Author = "Commenter_10",
                            ComedyTextId = 10,
                            CommentTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 394, DateTimeKind.Utc).AddTicks(137),
                            GptJoke = "Generated Joke 10",
                            JokeId = 0,
                            Snippet = "Snippet 10",
                            SnippetAuthor = "SnippetAuthor_10",
                            SnippetTimestamp = new DateTime(2024, 11, 6, 15, 51, 36, 394, DateTimeKind.Utc).AddTicks(138),
                            Text = "Sample Comment 10",
                            UserId = 0
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Friendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FriendId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserId");

                    b.ToTable("Friendships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FriendId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            FriendId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            FriendId = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            FriendId = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            FriendId = 6,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            FriendId = 7,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            FriendId = 8,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            FriendId = 9,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            FriendId = 10,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            FriendId = 1,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Joke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Jokes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 6, 15, 51, 36, 388, DateTimeKind.Utc).AddTicks(7413),
                            Text = "Dlaczego niebo jest niebieskie? Bo programista jeszcze nie skończył debugować!"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 11, 6, 15, 51, 36, 388, DateTimeKind.Utc).AddTicks(7420),
                            Text = "Dlaczego komputer był smutny? Bo miał zbyt dużo problemów!"
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CommentId = 5,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 6,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 7,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 8,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 9,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 10,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Reaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommentId")
                        .HasColumnType("integer");

                    b.Property<int?>("JokeId")
                        .HasColumnType("integer");

                    b.Property<string>("ReactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("JokeId");

                    b.HasIndex("UserId", "JokeId")
                        .IsUnique();

                    b.ToTable("Reactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            JokeId = 1,
                            ReactionType = "like",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            JokeId = 1,
                            ReactionType = "superlike",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            JokeId = 2,
                            ReactionType = "meh",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.SocialLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("SocialLogins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LinkedAt = new DateTime(2024, 11, 6, 15, 51, 36, 394, DateTimeKind.Utc).AddTicks(466),
                            Provider = "Google",
                            ProviderUserId = "google_user_1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            LinkedAt = new DateTime(2024, 11, 6, 15, 51, 36, 394, DateTimeKind.Utc).AddTicks(476),
                            Provider = "Facebook",
                            ProviderUserId = "facebook_user_1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            LinkedAt = new DateTime(2024, 11, 6, 15, 51, 36, 394, DateTimeKind.Utc).AddTicks(477),
                            Provider = "GitHub",
                            ProviderUserId = "github_user_2",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 6, 15, 51, 36, 394, DateTimeKind.Utc).AddTicks(420),
                            Email = "user1@example.com",
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "hashed_password_1",
                            Username = "user1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 11, 6, 15, 51, 36, 394, DateTimeKind.Utc).AddTicks(426),
                            Email = "user2@example.com",
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "hashed_password_2",
                            Username = "user2"
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Interests")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserProfile");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Interests = "Interests_1",
                            ProfilePictureUrl = "https://example.com/user1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Interests = "Interests_2",
                            ProfilePictureUrl = "https://example.com/user2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Interests = "Interests_3",
                            ProfilePictureUrl = "https://example.com/user3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Interests = "Interests_4",
                            ProfilePictureUrl = "https://example.com/user4.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Interests = "Interests_5",
                            ProfilePictureUrl = "https://example.com/user5.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Interests = "Interests_6",
                            ProfilePictureUrl = "https://example.com/user6.jpg"
                        },
                        new
                        {
                            Id = 7,
                            Interests = "Interests_7",
                            ProfilePictureUrl = "https://example.com/user7.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Interests = "Interests_8",
                            ProfilePictureUrl = "https://example.com/user8.jpg"
                        },
                        new
                        {
                            Id = 9,
                            Interests = "Interests_9",
                            ProfilePictureUrl = "https://example.com/user9.jpg"
                        },
                        new
                        {
                            Id = 10,
                            Interests = "Interests_10",
                            ProfilePictureUrl = "https://example.com/user10.jpg"
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.ComedyText", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.ComedyText", "ChildComedyText")
                        .WithOne("ParentComedyText")
                        .HasForeignKey("Toci.Haia.Database.Persistence.ComedyText", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.User", null)
                        .WithMany("ComedyTexts")
                        .HasForeignKey("UserId");

                    b.Navigation("ChildComedyText");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Comment", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.ComedyText", "ComedyText")
                        .WithMany("Comments")
                        .HasForeignKey("ComedyTextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.ComedyText", null)
                        .WithMany("Replies")
                        .HasForeignKey("ComedyTextId1");

                    b.HasOne("Toci.Haia.Database.Persistence.Joke", "Joke")
                        .WithMany("Comments")
                        .HasForeignKey("JokeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId");

                    b.HasOne("Toci.Haia.Database.Persistence.User", null)
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComedyText");

                    b.Navigation("Joke");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Friendship", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.User", "Friend")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Like", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Reaction", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Toci.Haia.Database.Persistence.Joke", "Joke")
                        .WithMany("Reactions")
                        .HasForeignKey("JokeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Comment");

                    b.Navigation("Joke");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.SocialLogin", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.User", "User")
                        .WithMany("SocialLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.ComedyText", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ParentComedyText")
                        .IsRequired();

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Comment", b =>
                {
                    b.Navigation("Reactions");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Joke", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.User", b =>
                {
                    b.Navigation("ComedyTexts");

                    b.Navigation("Comments");

                    b.Navigation("SocialLogins");
                });
#pragma warning restore 612, 618
        }
    }
}
