// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Toci.Haia.Database.Persistence;

#nullable disable

namespace Toci.Haia.Database.Persistence.Migrations
{
    [DbContext(typeof(ComedyDbContext))]
    [Migration("20240929145842_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Toci.Haia.Database.Persistence.ComedyText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ChildTextId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CommentTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ParentTextId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ComedyTexts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Author_1",
                            CommentTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8886),
                            Text = "Sample Comedy Text 1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Author_2",
                            CommentTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8891),
                            Text = "Sample Comedy Text 2"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Author_3",
                            CommentTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8892),
                            Text = "Sample Comedy Text 3"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Author_4",
                            CommentTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8893),
                            Text = "Sample Comedy Text 4"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Author_5",
                            CommentTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8894),
                            Text = "Sample Comedy Text 5"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Author_6",
                            CommentTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8896),
                            Text = "Sample Comedy Text 6"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Author_7",
                            CommentTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8897),
                            Text = "Sample Comedy Text 7"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Author_8",
                            CommentTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8898),
                            Text = "Sample Comedy Text 8"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Author_9",
                            CommentTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8899),
                            Text = "Sample Comedy Text 9"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Author_10",
                            CommentTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8900),
                            Text = "Sample Comedy Text 10"
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ComedyTextId")
                        .HasColumnType("integer");

                    b.Property<int?>("ComedyTextId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CommentTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GptJoke")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("integer");

                    b.Property<string>("Snippet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SnippetAuthor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SnippetTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComedyTextId");

                    b.HasIndex("ComedyTextId1");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Commenter_1",
                            ComedyTextId = 1,
                            CommentTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8933),
                            GptJoke = "Generated Joke 1",
                            Snippet = "Snippet 1",
                            SnippetAuthor = "SnippetAuthor_1",
                            SnippetTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8933),
                            Text = "Sample Comment 1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Commenter_2",
                            ComedyTextId = 2,
                            CommentTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8937),
                            GptJoke = "Generated Joke 2",
                            Snippet = "Snippet 2",
                            SnippetAuthor = "SnippetAuthor_2",
                            SnippetTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8937),
                            Text = "Sample Comment 2"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Commenter_3",
                            ComedyTextId = 3,
                            CommentTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8948),
                            GptJoke = "Generated Joke 3",
                            Snippet = "Snippet 3",
                            SnippetAuthor = "SnippetAuthor_3",
                            SnippetTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8948),
                            Text = "Sample Comment 3"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Commenter_4",
                            ComedyTextId = 4,
                            CommentTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8950),
                            GptJoke = "Generated Joke 4",
                            Snippet = "Snippet 4",
                            SnippetAuthor = "SnippetAuthor_4",
                            SnippetTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8950),
                            Text = "Sample Comment 4"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Commenter_5",
                            ComedyTextId = 5,
                            CommentTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8952),
                            GptJoke = "Generated Joke 5",
                            Snippet = "Snippet 5",
                            SnippetAuthor = "SnippetAuthor_5",
                            SnippetTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8953),
                            Text = "Sample Comment 5"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Commenter_6",
                            ComedyTextId = 6,
                            CommentTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8955),
                            GptJoke = "Generated Joke 6",
                            Snippet = "Snippet 6",
                            SnippetAuthor = "SnippetAuthor_6",
                            SnippetTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8955),
                            Text = "Sample Comment 6"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Commenter_7",
                            ComedyTextId = 7,
                            CommentTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8957),
                            GptJoke = "Generated Joke 7",
                            Snippet = "Snippet 7",
                            SnippetAuthor = "SnippetAuthor_7",
                            SnippetTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8957),
                            Text = "Sample Comment 7"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Commenter_8",
                            ComedyTextId = 8,
                            CommentTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8959),
                            GptJoke = "Generated Joke 8",
                            Snippet = "Snippet 8",
                            SnippetAuthor = "SnippetAuthor_8",
                            SnippetTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8960),
                            Text = "Sample Comment 8"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Commenter_9",
                            ComedyTextId = 9,
                            CommentTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8962),
                            GptJoke = "Generated Joke 9",
                            Snippet = "Snippet 9",
                            SnippetAuthor = "SnippetAuthor_9",
                            SnippetTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8962),
                            Text = "Sample Comment 9"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Commenter_10",
                            ComedyTextId = 10,
                            CommentTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8965),
                            GptJoke = "Generated Joke 10",
                            Snippet = "Snippet 10",
                            SnippetAuthor = "SnippetAuthor_10",
                            SnippetTimestamp = new DateTime(2024, 9, 29, 14, 58, 41, 848, DateTimeKind.Utc).AddTicks(8965),
                            Text = "Sample Comment 10"
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Friendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FriendId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserId");

                    b.ToTable("Friendships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FriendId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            FriendId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            FriendId = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            FriendId = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            FriendId = 6,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            FriendId = 7,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            FriendId = 8,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            FriendId = 9,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            FriendId = 10,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            FriendId = 1,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CommentId = 5,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 6,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 7,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 8,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 9,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 10,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "user1@example.com",
                            PasswordHash = "hash_user_1",
                            Username = "User_1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user2@example.com",
                            PasswordHash = "hash_user_2",
                            Username = "User_2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "user3@example.com",
                            PasswordHash = "hash_user_3",
                            Username = "User_3"
                        },
                        new
                        {
                            Id = 4,
                            Email = "user4@example.com",
                            PasswordHash = "hash_user_4",
                            Username = "User_4"
                        },
                        new
                        {
                            Id = 5,
                            Email = "user5@example.com",
                            PasswordHash = "hash_user_5",
                            Username = "User_5"
                        },
                        new
                        {
                            Id = 6,
                            Email = "user6@example.com",
                            PasswordHash = "hash_user_6",
                            Username = "User_6"
                        },
                        new
                        {
                            Id = 7,
                            Email = "user7@example.com",
                            PasswordHash = "hash_user_7",
                            Username = "User_7"
                        },
                        new
                        {
                            Id = 8,
                            Email = "user8@example.com",
                            PasswordHash = "hash_user_8",
                            Username = "User_8"
                        },
                        new
                        {
                            Id = 9,
                            Email = "user9@example.com",
                            PasswordHash = "hash_user_9",
                            Username = "User_9"
                        },
                        new
                        {
                            Id = 10,
                            Email = "user10@example.com",
                            PasswordHash = "hash_user_10",
                            Username = "User_10"
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Interests")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserProfile");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Interests = "Interests_1",
                            ProfilePictureUrl = "https://example.com/user1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Interests = "Interests_2",
                            ProfilePictureUrl = "https://example.com/user2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Interests = "Interests_3",
                            ProfilePictureUrl = "https://example.com/user3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Interests = "Interests_4",
                            ProfilePictureUrl = "https://example.com/user4.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Interests = "Interests_5",
                            ProfilePictureUrl = "https://example.com/user5.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Interests = "Interests_6",
                            ProfilePictureUrl = "https://example.com/user6.jpg"
                        },
                        new
                        {
                            Id = 7,
                            Interests = "Interests_7",
                            ProfilePictureUrl = "https://example.com/user7.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Interests = "Interests_8",
                            ProfilePictureUrl = "https://example.com/user8.jpg"
                        },
                        new
                        {
                            Id = 9,
                            Interests = "Interests_9",
                            ProfilePictureUrl = "https://example.com/user9.jpg"
                        },
                        new
                        {
                            Id = 10,
                            Interests = "Interests_10",
                            ProfilePictureUrl = "https://example.com/user10.jpg"
                        });
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.ComedyText", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.ComedyText", "ChildComedyText")
                        .WithOne("ParentComedyText")
                        .HasForeignKey("Toci.Haia.Database.Persistence.ComedyText", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.User", null)
                        .WithMany("ComedyTexts")
                        .HasForeignKey("UserId");

                    b.Navigation("ChildComedyText");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Comment", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.ComedyText", "ComedyText")
                        .WithMany("Comments")
                        .HasForeignKey("ComedyTextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.ComedyText", null)
                        .WithMany("Replies")
                        .HasForeignKey("ComedyTextId1");

                    b.HasOne("Toci.Haia.Database.Persistence.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId");

                    b.HasOne("Toci.Haia.Database.Persistence.User", null)
                        .WithMany("Comments")
                        .HasForeignKey("UserId");

                    b.Navigation("ComedyText");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Friendship", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.User", "Friend")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Like", b =>
                {
                    b.HasOne("Toci.Haia.Database.Persistence.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toci.Haia.Database.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.ComedyText", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ParentComedyText")
                        .IsRequired();

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Toci.Haia.Database.Persistence.User", b =>
                {
                    b.Navigation("ComedyTexts");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
